[tools]
# Programming Languages & Runtimes
go = "1.25.4"
java = "corretto-17"
node = "25"
scala = "2.12"
gradle = "9"
npm = "11"
sbt = "1.11"
mill = "latest"
coursier = "latest"
pnpm = "latest"

# Infrastructure Tools
argo = "latest"
gh = "latest"
goreleaser = "latest"
helm = "3"
jj = "latest"
k9s = "latest"
kubectl = "1.32"
kustomize = "latest"
lazydocker = "latest"
lazygit = "latest"
teleport-ent = "16"
terraform = "1.14.0"
tfenv = "latest"

# Databases
mysql = "8"
duckdb = "latest"
